version: 2

jobs:
  default-plan-apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init
          command: |
            terraform init -input=false -backend-config="bucket=${TF_BUCKET}" -backend-config="key=${TF_KEY}" -backend-config="region=${TF_REGION}"
      - run:
          name: terraform workspace
          command: |
            terraform workspace select default || terraform workspace new default
      - run:
          name: terraform plan
          command: |
            terraform plan -out tfapply -var-file variables.tfvars.default
      - persist_to_workspace:
          root: .
          paths:
            - .
  default-apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .
  default-plan-destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy -var-file variables.tfvars.default
      - persist_to_workspace:
          root: .
          paths:
            - .
  default-destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - default-plan-apply:
          filters:
            branches:
              only: master
      - default-hold-apply:
          type: approval
          requires:
            - default-plan-apply
      - default-apply:
          requires:
            - default-hold-apply
          filters:
            branches:
              only: master
      - default-plan-destroy:
          requires:
            - default-apply
          filters:
            branches:
              only: master
      - default-hold-destroy:
          type: approval
          requires:
            - default-plan-destroy
      - default-destroy:
          requires:
            - default-hold-destroy
          filters:
            branches:
              only: master
